shops:
    elefunds:
        path:
            /Users/chp/Web/elefunds/shopware
        web:
            http://localhost:8888/elefunds/shopware

commands:
    select_shop:
        Avantgarde\ShopwareCLI\Command\SelectShopCommand
    cache_clear:
        Avantgarde\ShopwareCLI\Command\CacheClearCommand
    plugin_list:
        Avantgarde\ShopwareCLI\Command\PluginListCommand
    plugin_uninstall:
        Avantgarde\ShopwareCLI\Command\PluginUninstallCommand